### ISSUE TITLE
wget is no longer supported by archiso

### ISSUE THREAD

**Issue by NewtonGimmick** [MatMoul/archfi#129]
will need to convert to curl.

**Comment by Euqcoral** [comment]
install wget by doing # pacman -Sy wget and then follow the normal procedure

**Comment by lan-vuhoang** [comment]
Could there be an easier way to download the script? I'm in Vietnam and I didn't exactly have the best mirror speeds.

**Comment by Euqcoral** [comment]
Ok. Install "reflector" with this command " # pacman -Sy reflector "

**Comment by lan-vuhoang** [comment]
Even syncing repos is a struggle. I usually get about 30kb/s with the default mirrorlist, let alone with the ~4MB `community` repo, and it tooks a VERY long time just to rank mirrors with reflector alone, since my usual parameters are `reflector --verbose -a 24 -p http -p https --sort rate --save /etc/pacman.d/mirrorlist`.

**Comment by Euqcoral** [comment]
Try this:       reflector -c Vietnam -p http --sort rate --save /etc/pacman.d/mirrorlist

**Comment by MatMoul** [comment]
wget to curl updated in #130
