### ISSUE TITLE
Change from yaourt to aurman

### ISSUE THREAD

**Issue by searedvandal** [MatMoul/archfi#29]
I just want to suggest maybe move away from yaourt and provide the option to install something like aurman instead.

https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table

**Comment by MatMoul** [comment]
In the past, I've provided a choice
https://github.com/MatMoul/archdi-pkg/blob/master/updates/menu#L9
I'll try to add new aur helpers...

**Comment by ejbolt** [comment]
I've personally found trizen to be very useful, and yay seems to be gaining traction too.  Both great helpers imo, although yay has been touch-and-go with tab completion.  Figured I'd put that out there.  Amazing scripts by the way man, I've installed Arch many many times manually and it's so nice to have something that is so straightforward like another Linux installer, but still has so many customization options, which is what we look for in Arch.  Keep up the awesome work :)

**Comment by MatMoul** [comment]
I've just implemented trisen, yay and aurman in the src branch (No other helpers are planned at this time).
I've added trizen as first position because it's compatible with octopi.
Now if you have more than one aurhelper installed, archdi use this priority : trizen, yay, aurman and yaourt.
aurman seem to be more for power user, it's possible that I add it as first priority but at last poisiton in the update menu.
before I make the relaese, you can test with `archdi -b src`

**Comment by ejbolt** [comment]
You're the man :) excellent choices all around.

**Comment by MatMoul** [comment]
Release out...
